### ISSUE TITLE
*555# does not work, ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by probonopd** [bildschirmtext/bildschirmtext#9]
`*555#` is not documented yet but i gather that it should show Wikipedia.

```
DOSBox version 0.74
Copyright 2002-2010 DOSBox Team, published under GNU GPL.
---
CONFIG:Loading primary settings from config file dosbox.conf
Neu-Ulm running.
MIXER:Got different values from SDL: freq 44100, blocksize 512
ALSA:Can't subscribe to MIDI port (65:0) nor (17:0)
MIDI:Opened device:none
Serial3: Opening ../tmp/ttyV0
Modem command: 'AT&F'
Modem command: 'ATX3DP01910'
showing page: '00000a'
compressed 497 down to 323
Sending pal/char: .OK
Sending text: .....................................OK
history: ['00000a']
links: {}
In: 0x1c
In: 0x1c
In: 0x1c
login ok
input_data: {'$command': '000001a'}
showing page: '000001a'
messages file not found
messages file not found
loading: '../data/00000/a.inc'
Sending pal/char: .........OK
Sending text: ........................................OK
history: ['00000a', '000001a']
links: {'#': '0', '7': '77'}
In: 0x1c
input_data: {'$navigation': ''}
Cept.tershowing page: '0a'
filename: 'a'
loading: '../data/0/a.inc'
Sending pal/char: .........OK
Sending text: ....................................OK
history: ['00000a', '000001a', '0a']
links: {'6': '10401131', '7': '78', '8': '8', '9': '9'}
In: 0x13
entering command mode
In: 0x35
self.__data:
['\x135                  ']
self.string:
'\x135'
In: 0x35
self.__data:
['\x1355                 ']
self.string:
'\x1355'
In: 0x35
self.__data:
['\x13555                ']
self.string:
'\x13555'
In: 0x1c
exited command mode
'<INI>555'
input_data: {'$command': '555'}
showing page: '555a'
Traceback (most recent call last):
  File "neu-ulm.py", line 603, in <module>
    ret = create_page(desired_pageid)
  File "neu-ulm.py", line 249, in create_page
    ret = Wikipedia_UI.create_page(pageid)
  File "/home/me/squashfs-root/usr/server/wikipedia.py", line 421, in create_page
    return Wikipedia_UI.create_wiki_page(int(pageid[3:-1]), ord(pageid[-1]) - ord("a"))
ValueError: invalid literal for int() with base 10: ''
2019/01/15 22:12:35 socat[22691] W waitpid(): child 22693 exited with status 1
2019/01/15 22:12:35 socat[22691] N socket 1 (fd 3) is at EOF
2019/01/15 22:12:36 socat[22691] N exiting with status 0
```

**Comment by probonopd** [comment]
Thereafter even `*0#` does not work anymore:

```
Serial3: COM port error: write failed!
Serial3: COM port error: write failed!
Serial3: COM port error: write failed!
Serial3: COM port error: write failed!
```

Probably it would be a good idea to wrap everything in `try: except:` so that even if a particular page cannot be rendered, the whole thing does not crash.

**Comment by mist64** [comment]
The Wikipedia namespace (temporarily at 555) needs a MediaWiki page id appended to work, e.g. *555704# for Wikipedia (de) page 704.

@probonopd: We have a mailing list where we announce/discuss this:
https://lists.hanse.de/mailman/listinfo/btx

And yes, I'll have to make everything way more crash resilient. The problem is that wrapping everything in try/catch right now will mask edge cases that I need to handle correctly first. Also, my Python sucks. :)

**Comment by probonopd** [comment]
@HammiKnuff not entirely:

```
input_data: {'$command': '555'}
showing page: '555a'
char resolution: 7*6
Traceback (most recent call last):
  File "neu-ulm.py", line 608, in <module>
    ret = create_page(desired_pageid)
  File "neu-ulm.py", line 251, in create_page
    ret = Wikipedia_UI.create_page(pageid, basedir)
  File "/tmp/.mount_BildscM5oZCB/usr/server/wikipedia.py", line 370, in create_page
    return Wikipedia_UI.create_search_page(basedir)
  File "/tmp/.mount_BildscM5oZCB/usr/server/wikipedia.py", line 325, in create_search_page
    (palette, drcs, chars) = Image_UI.cept_from_image(basedir + "wikipedia.png")
  File "/tmp/.mount_BildscM5oZCB/usr/server/image.py", line 32, in cept_from_image
    image = image.resize((res_x * 6, res_y * 10), resample = Image.LANCZOS)
AttributeError: 'module' object has no attribute 'LANCZOS'
```

**Comment by mist64** [comment]
It seems your PIL/Pillow library doesn't support the LANCZOS algorithm when scaling down the image. It works on my Mac as well as my Ubuntu VM:

$ pip3 list | grep -i Pil
Pillow         5.4.1  

$ pip3 list | grep -i pil
Pillow (5.2.0)
